name: temres_apps
version: 1.0.12+12
publish_to: none
description: Temres 2024.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^4.0.3
  get_storage: ^2.0.3
  hexcolor: ^3.0.1
  http: ^0.13.4
  flutter_svg: ^2.0.2
  location: ^4.2.0
  path_provider: ^2.0.13
  path: ^1.8.3
  rxdart: ^0.27.2
  intl: ^0.18.0
  flutter_typeahead: ^4.0.0
  file_picker: ^5.2.5
  flutter_image_compress: ^1.1.0
  image_cropper: ^3.0.1
  camera: ^0.10.3+2
  # animated_floating_buttons: ^0.0.1
  flutter:
    sdk: flutter
  cron: ^0.5.1
  dropdown_button2: ^2.1.4
  group_radio_button: ^1.3.0
  onesignal_flutter: ^5.0.0
  hive: ^2.2.3

dev_dependencies:
  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/png/logo.png"
  color: "#fff"
  background_color: "#fff"
  adaptive_icon_background: "#fff"
  adaptive_icon_foreground: "assets/png/logo.png"
  android:
    generate: true
    color: "#fff"
    background_color: "#fff"


    

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
